
import { Story, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const categories: Category[] = [
  { id: '1', name: 'Romantik' },
  { id: '2', name: 'Mafya' },
  { id: '3', name: 'Dram' },
  { id: '4', name: 'Fantastik' },
  { id: '5', name: 'Gizem' },
  { id: '6', name: 'Macera' },
];

const DEFAULT_LONG_SYNOPSIS = "Kaderin cilvesiyle bir araya gelen iki yabancı, kendilerini beklemedikleri bir fırtınanın ortasında bulurlar. Geçmişin gölgeleri peşlerini bırakmazken, aralarındaki çekim her geçen gün daha da dayanılmaz bir hal alır.\n\nSırlar açığa çıktıkça, sadakatler test edilecek ve aşkın en saf hali ile en karanlık yüzü karşı karşıya gelecektir. Her sayfasında soluksuz kalacağınız bu hikayede, imkansızın sınırları zorlanıyor.\n\nİstanbul'un dar sokaklarından görkemli yalılara uzanan bu yolculukta, sadece hayatta kalmak değil, gerçekten yaşamak için savaşmaları gerekecek. Kalbinizin ritmini değiştirecek bir destan sizi bekliyor.";

export const stories: Story[] = [
  {
    id: 's1',
    title: 'Gece Yarısı Güneşi',
    author: 'Elif Şafak',
    synopsis: 'Eski bir konağın tozlu rafları arasında başlayan imkansız bir aşk hikayesi.',
    longSynopsis: "Eski bir konağın tozlu rafları arasında başlayan imkansız bir aşk hikayesi. Yıllardır kimsenin adım atmadığı kütüphane odasında bulunan gizemli bir mektup, iki ailenin on yıllardır süren düşmanlığını yeniden alevlendirir.\n\nGenç ve idealist bir araştırmacı olan Leyla, bu mektubun peşine düştüğünde konağın varisi Kerem ile tanışır. Başta birbirlerinden nefret eden bu iki genç, mektubun ardındaki trajik gerçeği öğrendikçe birbirlerine bağlanırlar.\n\nAncak geçmişin günahları, günümüzün mutluluğuna izin verecek mi? Gece yarısı doğan bir güneş gibi, karanlığın en koyu anında başlayan bu aşk, her şeyi yakıp kül mü edecek yoksa dünyayı mı aydınlatacak?",
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-1')?.imageUrl || '',
    readCount: 125400,
    rating: 4.8,
    category: 'Romantik',
    tags: ['Romantik', 'Tarihi', 'Gizem', 'Aşk'],
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 's2',
    title: 'Karanlık Lordun Varisi',
    author: 'Zeynep Sahra',
    synopsis: 'Büyülü bir krallığın yıkılışından sonra küllerinden doğan genç bir savaşçının destanı.',
    longSynopsis: DEFAULT_LONG_SYNOPSIS,
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-2')?.imageUrl || '',
    readCount: 89000,
    rating: 4.7,
    category: 'Fantastik',
    tags: ['Fantastik', 'Aksiyon', 'Epik', 'Büyü'],
    isPopular: true,
  },
  {
    id: 's3',
    title: 'Sokakların Kanunu',
    author: 'Ahmet Ümit',
    synopsis: 'Yeraltı dünyasının acımasız kuralları arasında hayatta kalmaya çalışan bir dostluk.',
    longSynopsis: DEFAULT_LONG_SYNOPSIS,
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-3')?.imageUrl || '',
    readCount: 210000,
    rating: 4.9,
    category: 'Mafya',
    tags: ['Mafya', 'Suç', 'İntikam', 'Dram'],
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 's4',
    title: 'Son Yaprak Dökümü',
    author: 'Reşat Nuri',
    synopsis: 'Parçalanan bir ailenin hüzünlü ve umut dolu yeniden birleşme çabası.',
    longSynopsis: DEFAULT_LONG_SYNOPSIS,
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-4')?.imageUrl || '',
    readCount: 45000,
    rating: 4.5,
    category: 'Dram',
    tags: ['Dram', 'Aile', 'Hüzün', 'Klasik'],
    isPopular: false,
  },
  {
    id: 's5',
    title: 'Mühürlü Kapı',
    author: 'Peyami Safa',
    synopsis: 'İstanbul\'un gizli geçitlerinde saklı kalmış antik bir sırrın peşinde tehlikeli bir takip.',
    longSynopsis: DEFAULT_LONG_SYNOPSIS,
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-5')?.imageUrl || '',
    readCount: 78000,
    rating: 4.6,
    category: 'Gizem',
    tags: ['Gizem', 'Gerilim', 'İstanbul', 'Antik'],
    isPopular: true,
  },
  {
    id: 's6',
    title: 'Zirve Yolcuları',
    author: 'Sabahattin Ali',
    synopsis: 'Doğanın kalbinde, insanın kendi sınırlarını keşfettiği unutulmaz bir tırmanış macerası.',
    longSynopsis: DEFAULT_LONG_SYNOPSIS,
    imageUrl: PlaceHolderImages.find(img => img.id === 'book-6')?.imageUrl || '',
    readCount: 32000,
    rating: 4.4,
    category: 'Macera',
    tags: ['Macera', 'Doğa', 'Psikolojik', 'İnsan'],
    isPopular: false,
  }
];
